give error if module already gotten

diff --git a/pup-mod-get b/pup-mod-get
--- a/pup-mod-get
+++ b/pup-mod-get
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#  Copyright 2007 Simon Hürlimann <simon.huerlimann@cyt.ch>
+#  Copyright 2007-2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -32,7 +32,7 @@ fi
 # Operations
 # ==========
 function get_module() {
-local module=$1
+local module_uri=$1
 
 	cd $MODULES_PATH
 	darcs get $MODULES_REPOSITORY/$module
@@ -40,6 +40,14 @@ local module=$1
 
 # Main
 # ====
+module_uri="$MODULES_REPOSITORY/$module"
+module_path="$MODULES_PATH/$module"
+
+if [ -d "$module_path" ] ; then
+	echo "[ERROR] module '$MODULE' already at '$module_path', exiting." >&2
+	exit 1
+fi
+
 pushd . >/dev/null
 	get_module $MODULE
 popd >/dev/null
